USE [MSPAArchive]
GO

/****** Object:  Table [dbo].[PagesArchived]    Script Date: 2015-06-22 11:11:46 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PagesArchived](
	[page_id] [int] NOT NULL,
 CONSTRAINT [PK_PagesArchived] PRIMARY KEY CLUSTERED 
(
	[page_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

